server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  output:
    ansi:
      enabled: always
  application:
    name: admin-service
  cloud:
    compatibility-verifier:
      enabled: false




